apiVersion: v2
name: vb-load-test
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
- name: nxs-universal-chart
  version: "2.8.1"
  repository: https://registry.nixys.io/chartrepo/public
  export-values:
  - parent: werf
    child: werf